// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvQqSH9sUyHqC19W0eXyjGFqDgAowFztM',
    appId: '1:242383778526:web:4fa770bccebe180a39c84f',
    messagingSenderId: '242383778526',
    projectId: 'smoking-cessation-78e14',
    authDomain: 'smoking-cessation-78e14.firebaseapp.com',
    storageBucket: 'smoking-cessation-78e14.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpwntoyQxjluM49OJ6aMGhnsBwCwQxHco',
    appId: '1:242383778526:android:b12c3db54f7bf2cd39c84f',
    messagingSenderId: '242383778526',
    projectId: 'smoking-cessation-78e14',
    storageBucket: 'smoking-cessation-78e14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5U6rWhxH87POeQJVEhp_yAx7HnQuh8ZY',
    appId: '1:242383778526:ios:b4332a61bf22f74439c84f',
    messagingSenderId: '242383778526',
    projectId: 'smoking-cessation-78e14',
    storageBucket: 'smoking-cessation-78e14.firebasestorage.app',
    iosClientId: '242383778526-mia579gpv0j7ak35g76rhpbc7sll9kkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.breatheFree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5U6rWhxH87POeQJVEhp_yAx7HnQuh8ZY',
    appId: '1:242383778526:ios:b4332a61bf22f74439c84f',
    messagingSenderId: '242383778526',
    projectId: 'smoking-cessation-78e14',
    storageBucket: 'smoking-cessation-78e14.firebasestorage.app',
    iosClientId: '242383778526-mia579gpv0j7ak35g76rhpbc7sll9kkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.breatheFree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvQqSH9sUyHqC19W0eXyjGFqDgAowFztM',
    appId: '1:242383778526:web:f8f96976abfaffa039c84f',
    messagingSenderId: '242383778526',
    projectId: 'smoking-cessation-78e14',
    authDomain: 'smoking-cessation-78e14.firebaseapp.com',
    storageBucket: 'smoking-cessation-78e14.firebasestorage.app',
  );
}